trigger:
- master

pr:
- master

stages:
  - stage: BuildSite
    displayName: "build.yml"
    dependsOn: [] # run in parallel with core build
    jobs:
      - job: BuilUI
        displayName: "Next JS build"
        timeoutInMinutes: 10
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - template: build-site.yml
